### ISSUE TITLE
Configurable key file allowed permissions

### ISSUE THREAD

**Issue by stac47** [rocketjob/symmetric-encryption#170]
Hello dear maintainers,

I wanted to migrate the version of this gem from 3.9.x to 4.6.0 and realised that in the PR https://github.com/reidmorrison/symmetric-encryption/pull/112, a test on permission of the key file which results in the following error:

```
 SymmetricEncryption::ConfigError: Symmetric Encryption key file '/etc/platform/keys/encryption_production.key' has the wrong permissions: 100644. Expected 100600 or 100400.
```

I agree with this feature and can understand it is what we want by default when we deploy an application without using containers. But with containers at best, the application runs in a space where only one default user (besides `root`) is defined or directly without defining any user and running the application as root. In both case, when somebody break into a container, one gets the access to the mounted files whatever the permission be `600` or `644`.

Another problem is that when your application is deployed within a kubernetes cluster, and the files are mounted into your container with the following deployment configuration:

```
      containers: 
      - name: "myapp"
        image: "myapp-master-134476d3"
       [...]
        volumeMounts:
          - name: "myapp-encryption-secrets-binary"
            mountPath: "/etc/platform/keys"
            readOnly: true
      volumes: 
        - name: myapp-encryption-secrets-binary
          secret:
            items:
            - key: encryption-key
              path: encryption_production.key
            - key: encryption-iv
              path: encryption_production.iv
            secretName: mysecret-encryption-binary-b64
```

Using `readOnly: true` (which ensure the container cannot write the volume https://kubernetes.io/docs/concepts/storage/volumes/#read-only-mounts) is mounted with `644` permissions.

So my question is, provided we cannot tune the way the files are monted in k8s (which I am not sure), do you think we could add a configuration to be more permissive in the permission validation?

Thanks in advance for your attention,
Regards,
